export enum RejectionCode {
  MALFORMED_EVIDENCE = "MALFORMED_EVIDENCE",
  INVALID_LINEAGE = "INVALID_LINEAGE",
  REPLAY_CONFLICT = "REPLAY_CONFLICT",
  ORDERING_AMBIGUITY = "ORDERING_AMBIGUITY",
  STRUCTURAL_CORRUPTION = "STRUCTURAL_CORRUPTION",
  INVALID_SERIALIZATION = "INVALID_SERIALIZATION",
  CERTIFICATION_CONTAMINATION = "CERTIFICATION_CONTAMINATION"
}

export const REJECTION_CODES: readonly RejectionCode[] =
  Object.freeze([
    RejectionCode.MALFORMED_EVIDENCE,
    RejectionCode.INVALID_LINEAGE,
    RejectionCode.REPLAY_CONFLICT,
    RejectionCode.ORDERING_AMBIGUITY,
    RejectionCode.STRUCTURAL_CORRUPTION,
    RejectionCode.INVALID_SERIALIZATION,
    RejectionCode.CERTIFICATION_CONTAMINATION
  ]);
